# Generated by Django 4.2.6 on 2023-10-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_data_flattenedjson_input_json_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlattenedJson',
            new_name='FlattenedJsonModel',
        ),
        migrations.RenameField(
            model_name='flattenedjsonmodel',
            old_name='flattened_json',
            new_name='flattenedJson',
        ),
        migrations.RenameField(
            model_name='flattenedjsonmodel',
            old_name='input_json',
            new_name='inputJson',
        ),
    ]
